sonar.projectKey=Tarek94000_PRJ-DevOps
sonar.organization=Tarek94000
sonar.projectName=DevOps Reservation Project
sonar.sources=backend
sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
sonar.sourceEncoding=UTF-8
